<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>
    <?php echo $this->title;?>
    </title>

    <!-- DEFAULT LIBRARY -->
	<link  href="/public/frontLib/bootsrap/css/bootstrap.css" rel="stylesheet">
	<script src="/public/frontLib/js/jquery.min.js"></script>
	<script src="/public/frontLib/bootsrap/js/bootstrap.min.js"></script>
	<script src="/public/frontLib/js/underscore.min.js"></script>
	<script src="/public/frontLib/js/backbone-min.js"></script>

	<!-- Additional Libary -->
 
 
 	<!-- CSS For Toolbar -->
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style>

  </head>

  <body>
  
  <!-- TOOLBAR -->
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Project name</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="#">Home</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
